version: "{build}"

build:
  verbosity: normal

environment:
  global:
    STACK_ROOT: "c:\\sr"

cache:
- C:\sr -> stack.yaml                            # The stack root dir.
- C:\Users\appveyor\AppData\Local\Programs\stack\i386-windows

deploy: off

install:
  ps: |
    bash -c 'curl -Lso stack.zip -L --insecure http://www.stackage.org/stack/windows-i386'
    7z x stack.zip stack.exe
    mkdir C:\stack
    mv stack.exe C:\stack

    # The URL keeps changing from release to release and old versions
    # aren't kept around. In order to prevent the package from
    # stopping to work, we automatically find the latest version:

    $baseUrl='http://cran.at.r-project.org/bin/windows/base/'
    $wc = New-Object System.Net.WebClient
    if(!($wc.DownloadString($baseUrl) -match "R-(\d\.\d\.\d)-win.exe")) {
      throw "Unable to determine latest version from $baseUrl"
    }
    $wc.DownloadFile("$baseUrl$($Matches[0])", "$pwd\Rinstaller.exe")
    Start-Process -FilePath .\Rinstaller.exe -ArgumentList "/VERYSILENT /DIR=C:\R" -NoNewWindow -Wait

build_script:
  - set PATH=C:\stack;C:\R\bin\i386;%PATH%
  - stack --no-terminal setup > nul
  - stack --no-terminal --extra-lib-dirs="C:\R\bin\i386" --extra-include-dirs="C:\R\include" build --test inline-r H
