resolver: lts-20.11

packages:
- examples
- H
- IHaskell
- inline-r

extra-deps:
  - ihaskell-blaze-0.3.0.1
  - hashable-1.3.5.0
  - rest-rewrite-0.4.1
  - smtlib-backends-0.3
  - smtlib-backends-process-0.3
  - liquidhaskell-0.9.2.5.0
  - liquidhaskell-boot-0.9.2.5.0
  - liquid-fixpoint-0.9.2.5
  - liquid-prelude-0.9.2.5

nix:
  shell-file: ./shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]
