resolver: nightly-2025-12-15

packages:
- examples
- H
- IHaskell
- inline-r

extra-deps:
  - ihaskell-blaze-0.3.0.1
  - liquidhaskell-0.9.12.2.1
  - liquidhaskell-boot-0.9.12.2.1
  - liquid-fixpoint-0.9.6.3.5
  - liquid-prelude-0.9.12.2.1

nix:
  shell-file: ./shell.nix
  path: ["nixpkgs=./nixpkgs.nix"]
