packages:
- examples
- H
- IHaskell
- inline-r
resolver: lts-5.10

docker:
  # Disabled by default. Use --docker on command line to enable.
  enable: false
  repo: tweag/haskellr:latest

nix:
    enable: false
    packages:
    - ncurses
    - pkgconfig
    - python34Packages.ipython
    - python34Packages.jupyter_client
    - python34Packages.notebook
    - R
    - zeromq
    - zlib
    ## Right now, using just packages: is OK on Linux, not OSX
    #shell-file: ./shell.nix
